In [39]:
# np.dot, np.matmul, and np.multiply
# np.dot returns the scalar or dot product of two arrays. 
# np.matmul returns the matrix product of two arrays
# np.multiply returns the element-wise matrix multiplication of two arrays
    # np.multiply will give out hadamard product as output
# * operation: return hadamard product of array, matrix product of two matrix

# There are three kinds of products: matmul product, hadamard product, and kronecker product in matrix multiplication
import numpy as np

# Create two matrices
# A = np.array([[1, 2], [3, 4]])
# B = np.array([[5, 6], [7, 8]])

A = np.mat([[1, 2], [3, 4]])
B = np.mat([[5, 6], [7, 8]])


# A2 = np.mat(np.array([[1, 2], [3, 4]]))
# B2 = np.mat(np.array([[5, 6], [7, 8]]))

# Multiply the matrices
C1 = np.dot(A, B)
C2 = np.matmul(A, B)
C3 = np.multiply(A, B)
C4 = A*B
# Print the product
print("C1\n", C1)
print("C2\n", C2)
print("C3\n", C3)
print("C4\n", C4)


C1
 [[19 22]
 [43 50]]
C2
 [[19 22]
 [43 50]]
C3
 [[ 5 12]
 [21 32]]
C4
 [[19 22]
 [43 50]]


In [9]:
import random

def generate_random_list():
    values = [1, 2, 3, 4]
    random.shuffle(values)
    return [values[:2], values[2:]]

print(generate_random_list())

[[4, 1], [3, 2]]


In [19]:
import numpy as np

def generate_random_matrices(rows, columns):
    matrix1 = np.random.randint(100, size=(rows, columns))
    matrix2 = np.random.randint(100, size=(rows, columns))
    return matrix1, matrix2
matrix_A, matrix_B = generate_random_matrices(2, 2)
print(matrix_A)
print(matrix_B)
print(np.dot(matrix_A, matrix_B))

[[ 6 54]
 [73  6]]
[[38 70]
 [25 71]]
[[1578 4254]
 [2924 5536]]


In [20]:
print(np.matmul(np.mat(matrix_A), np.mat(matrix_B)))

[[1578 4254]
 [2924 5536]]


In [37]:
import time
import numpy as np

def generate_random_matrices(rows, columns):
    matrix1 = np.random.randint(100, size=(rows, columns))
    matrix2 = np.random.randint(100, size=(rows, columns))
    return matrix1, matrix2
matrix_A, matrix_B = generate_random_matrices(10, 10)

def algorithm1(x, y):
    return np.dot(x, y)

def algorithm2(x, y):
    return np.matmul(x, y)

def algorithm3(x, y):
    if isinstance(x, np.matrix) and isinstance(y, np.matrix):
        return x*y
    try:
        x = np.mat(x)
        y = np.mat(y)
        return x*y
    except Exception:
        return None

matrix = [[1, 2], [3, 4]]

start_time = time.time()
product1 = algorithm1(matrix_A, matrix_B)
end_time = time.time()
print(f"Algorithm 1 took {end_time - start_time} seconds")

start_time = time.time()
product2=algorithm2(matrix_A, matrix_B)
end_time = time.time()
print(f"Algorithm 2 took {end_time - start_time} seconds")


start_time = time.time()
product3=algorithm3(matrix_A, matrix_B)
end_time = time.time()
print(f"Algorithm 3 took {end_time - start_time} seconds")


# print(product1)
# print(product2)
# print(product3)
np.savetxt('product1.txt', product1)
np.savetxt('product2.txt', product2)
np.savetxt('product3.txt', product3)

Algorithm 1 took 0.0 seconds
Algorithm 2 took 0.0 seconds
Algorithm 3 took 0.0 seconds


In [ ]:
import unittest
import numpy as np

class TestMatrices(unittest.TestCase):
    def test_matrices_equal(self):
        matrix1 = np.loadtxt('product1.txt')
        matrix2 = np.loadtxt('product2.txt')
        np.testing.assert_array_equal(matrix1, matrix2)

if __name__ == '__main__':
    unittest.main()

In [2]:
import time
import random

def find_minimum(numbers, step):
    minimum = float("inf")
    for i in range(0, len(numbers), step):
        if numbers[i] < minimum:
            minimum = numbers[i]
    return minimum

numbers = [random.randint(0, 1000) for _ in range(1000)]

step = 1
runtimes = []

for _ in range(10):
    start_time = time.time()
    find_minimum(numbers, step)
    runtime = time.time() - start_time
    runtimes.append(runtime)

    if len(runtimes) >= 2 and runtimes[-1] > runtimes[-2]:
        step += 1

print("Optimal step:", step)

Optimal step: 1


In [ ]:
import time
import timeit
import numpy as np

def generate_random_matrices(rows, columns):
    matrix1 = np.random.randint(100, size=(rows, columns))
    matrix2 = np.random.randint(100, size=(rows, columns))
    return matrix1, matrix2
matrix_A, matrix_B = generate_random_matrices(10, 10)

def algorithm1(x, y):
    return np.dot(x, y)

def algorithm2(x, y):
    return np.matmul(x, y)

def algorithm3(x, y):
    if isinstance(x, np.matrix) and isinstance(y, np.matrix):
        return x*y
    try:
        x = np.mat(x)
        y = np.mat(y)
        return x*y
    except Exception:
        return None

# check time 
start_time = time.time()
product1 = algorithm1(matrix_A, matrix_B)
end_time = time.time()
print(f"Algorithm 1 took {end_time - start_time} seconds")

start_time = time.time()
product2=algorithm2(matrix_A, matrix_B)
end_time = time.time()
print(f"Algorithm 2 took {end_time - start_time} seconds")


start_time = time.time()
product3=algorithm3(matrix_A, matrix_B)
end_time = time.time()
print(f"Algorithm 3 took {end_time - start_time} seconds")


print(timeit.timeit(lambda:algorithm1(matrix_A, matrix_B), number=10000))
print(timeit.timeit(lambda:algorithm2(matrix_A, matrix_B), number=10000))
print(timeit.timeit(lambda:algorithm3(matrix_A, matrix_B), number=10000))
# print(product1)
# print(product2)
# print(product3)
# np.savetxt('product1.txt', product1)
# np.savetxt('product2.txt', product2)
# np.savetxt('product3.txt', product3)

In [3]:
import time

def time_function(func, *args):
    start_time = time.time()
    func(*args)
    return time.time() - start_time

def add(a, b):
    return a + b

def multiply(a, b):
    return a * b

add_time = time_function(add, 1, 2)
multiply_time = time_function(multiply, 3, 4)

print("Add time:", add_time)
print("Multiply time:", multiply_time)

Add time: 0.0
Multiply time: 0.0


In [ ]:
import itertools
def multiply_matrices_stride(A, B, stride):
    result = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]
    for i, j in itertools.product(range(0, len(A), stride), range(0, len(B[0]), stride)):
        for k, ii in itertools.product(range(0, len(B), stride), range(i, min(i + stride, len(A)))):
            for jj, kk in itertools.product(range(j, min(j + stride, len(B[0]))), range(k, min(k + stride, len(B)))):
                result[ii][jj] += A[ii][kk] * B[kk][jj]
    return result

A = [[1, 2], [3, 4]]
B = [[5, 6], [7, 8]]

result = multiply_matrices_stride(A, B, 1)
print(result)

In [ ]:
import itertools
def multiply_matrices_stride(A, B, stride):
    result = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]
    for i, j in itertools.product(range(0, len(A), stride), range(0, len(B[0]), stride)):
        for k, ii in itertools.product(range(0, len(B), stride), range(i, min(i + stride, len(A)))):
            for jj, kk in itertools.product(range(j, min(j + stride, len(B[0]))), range(k, min(k + stride, len(B)))):
                result[ii][jj] += A[ii][kk] * B[kk][jj]
    return result

A = [[1, 2], [3, 4]]
B = [[5, 6], [7, 8]]

result = multiply_matrices_stride(A, B, 1)
print(result)

In [4]:
def multiply_matrices_stride(A, B, stride):
    result = [[0 for j in range(len(B[0]))] for i in range(len(A))]
    for i in range(0, len(A), stride):
        for j in range(0, len(B[0]), stride):
            for k in range(0, len(B), stride):
                for ii in range(i, min(i + stride, len(A))):
                    for jj in range(j, min(j + stride, len(B[0]))):
                        for kk in range(k, min(k + stride, len(B))):
                            result[ii][jj] += A[ii][kk] * B[kk][jj]
    return result

A = [[1, 2], [3, 4]]
B = [[5, 6], [7, 8]]

result = multiply_matrices_stride(A, B, 1)
print(result)

[[19, 22], [43, 50]]


In [5]:
import time
import numpy as np

def multiply_matrices_stride(A, B, stride):
    result = [[0 for j in range(len(B[0]))] for i in range(len(A))]
    for i in range(0, len(A), stride):
        for j in range(0, len(B[0]), stride):
            for k in range(0, len(B), stride):
                for ii in range(i, min(i + stride, len(A))):
                    for jj in range(j, min(j + stride, len(B[0]))):
                        for kk in range(k, min(k + stride, len(B))):
                            result[ii][jj] += A[ii][kk] * B[kk][jj]
    return result

A = np.random.rand(100, 100)
B = np.random.rand(100, 100)

for stride in [1, 2, 4, 8]:
    start_time = time.time()
    multiply_matrices_stride(A, B, stride)
    print("Stride %d: %s seconds" % (stride, time.time() - start_time))

Stride 1: 1.5579826831817627 seconds
Stride 2: 0.7737984657287598 seconds
Stride 4: 0.585547924041748 seconds
Stride 8: 0.5074095726013184 seconds
